"""LLM provider abstraction with role-specific clients."""

from __future__ import annotations
import json, os
from abc import ABC, abstractmethod
from typing import Any
from openai import OpenAI
import httpx

from app.config import VALID_LLM_ROLES, get_llm_role_config, load_config
from app.llm.usage_tracker import estimate_tokens, record_llm_usage
from app.net import tls_verify_enabled


class LLMProvider(ABC):
    def __init__(self, role: str):
        self.role = role
        self.role_cfg = get_llm_role_config(role)
        self.model = self.role_cfg.model
        self.provider_name = self.role_cfg.provider

    def _budget_prompt(self, prompt: str) -> tuple[str, bool]:
        max_chars = self.role_cfg.max_input_tokens * 4
        if len(prompt) > max_chars:
            return prompt[:max_chars], True
        return prompt, False

    @abstractmethod
    def complete_json(self, prompt: str) -> dict: ...

    @abstractmethod
    def complete_text(self, prompt: str) -> str: ...


class MockProvider(LLMProvider):
    def complete_json(self, prompt: str) -> dict:
        prompt, _ = self._budget_prompt(prompt)
        out = {"ok": True}
        if "ROUTER_PLAN" in prompt:
            out = {"intent": "comparison", "entities": [], "filters": {"year_gte": 2024}, "store_weights": {"vector": 0.4, "graph": 0.2, "result": 0.3, "obsidian": 0.1}, "retrieval_budget": {"vector": 8, "graph": 4, "result": 6, "obsidian": 4}, "response_mode": "report"}
        elif "EXTRACTION" in prompt:
            payload = _extract_payload_from_prompt(prompt)
            chunks = payload.get("chunks", [])
            cid = chunks[0].get("chunk_id", "c0") if chunks else "c0"
            out = {"facts": [{"text": "Mock extracted fact", "evidence_chunk_ids": [cid], "confidence": 0.7}], "claims": [], "interpretations": [], "results": []}
        record_llm_usage(role=self.role, provider=self.provider_name, model=self.model, input_tokens=estimate_tokens(prompt), output_tokens=estimate_tokens(json.dumps(out)), source_module="llm_provider", status="success")
        return out

    def complete_text(self, prompt: str) -> str:
        prompt, _ = self._budget_prompt(prompt)
        text = "Grounded summary generated by mock provider."
        record_llm_usage(role=self.role, provider=self.provider_name, model=self.model, input_tokens=estimate_tokens(prompt), output_tokens=estimate_tokens(text), source_module="llm_provider", status="success")
        return text


class OpenAICompatibleProvider(LLMProvider):
    def __init__(self, role: str):
        super().__init__(role)
        cfg = load_config()
        key = cfg.llm.openai_api_key or os.getenv(self.role_cfg.api_key_env or "OPENAI_API_KEY")
        if not key:
            raise ValueError("Missing OpenAI API key")
        kwargs: dict[str, Any] = {"api_key": key}
        if self.role_cfg.base_url:
            kwargs["base_url"] = self.role_cfg.base_url
        kwargs["http_client"] = httpx.Client(verify=tls_verify_enabled())
        self.client = OpenAI(**kwargs)

    def complete_json(self, prompt: str) -> dict:
        prompt, truncated = self._budget_prompt(prompt)
        if truncated:
            print(f"[llm:{self.role}] prompt truncated to role budget")
        r = self.client.chat.completions.create(model=self.model, temperature=self.role_cfg.temperature, response_format={"type": "json_object"}, max_completion_tokens=self.role_cfg.max_output_tokens, messages=[{"role": "user", "content": prompt}])
        text = r.choices[0].message.content or "{}"
        u = getattr(r, "usage", None)
        in_tok = getattr(u, "prompt_tokens", None) or estimate_tokens(prompt)
        out_tok = getattr(u, "completion_tokens", None) or estimate_tokens(text)
        try:
            parsed = _safe_json_loads(text)
            record_llm_usage(role=self.role, provider=self.provider_name, model=self.model, input_tokens=in_tok, output_tokens=out_tok, source_module="llm_provider", status="success")
            return parsed
        except Exception as exc:
            fallback = _fallback_json_response(prompt)
            record_llm_usage(role=self.role, provider=self.provider_name, model=self.model, input_tokens=in_tok, output_tokens=estimate_tokens(json.dumps(fallback)), source_module="llm_provider", status="error", error_message=str(exc))
            print(f"[llm:{self.role}] fallback JSON parse: {exc}")
            return fallback

    def complete_text(self, prompt: str) -> str:
        prompt, truncated = self._budget_prompt(prompt)
        if truncated:
            print(f"[llm:{self.role}] prompt truncated to role budget")
        r = self.client.chat.completions.create(model=self.model, temperature=self.role_cfg.temperature, max_completion_tokens=self.role_cfg.max_output_tokens, messages=[{"role": "user", "content": prompt}])
        text = (r.choices[0].message.content or "").strip()
        u = getattr(r, "usage", None)
        record_llm_usage(role=self.role, provider=self.provider_name, model=self.model, input_tokens=getattr(u, "prompt_tokens", None) or estimate_tokens(prompt), output_tokens=getattr(u, "completion_tokens", None) or estimate_tokens(text), source_module="llm_provider", status="success")
        return text


def build_provider(role: str) -> LLMProvider:
    if role not in VALID_LLM_ROLES:
        raise ValueError(f"Unknown LLM role: {role}. Valid roles: {', '.join(VALID_LLM_ROLES)}")
    cfg = get_llm_role_config(role)
    if not cfg.enabled or cfg.provider == "mock":
        return MockProvider(role)
    if cfg.provider == "openai":
        try:
            return OpenAICompatibleProvider(role)
        except Exception as e:
            print(f"[llm:{role}] fallback to mock: {e}")
            return MockProvider(role)
    return MockProvider(role)


def render_json_prompt(template: str, payload: dict) -> str:
    return template + "\n\nINPUT:\n" + json.dumps(payload, indent=2)




def _fallback_json_response(prompt: str) -> dict:
    if "ROUTER_PLAN" in prompt:
        return {"intent": "comparison", "entities": [], "filters": {"year_gte": 2024}, "store_weights": {"vector": 0.4, "graph": 0.2, "result": 0.3, "obsidian": 0.1}, "retrieval_budget": {"vector": 8, "graph": 4, "result": 6, "obsidian": 4}, "response_mode": "report"}
    if "EXTRACTION" in prompt:
        payload = _extract_payload_from_prompt(prompt)
        chunks = payload.get("chunks", [])
        cid = chunks[0].get("chunk_id", "c0") if chunks else "c0"
        return {"facts": [{"text": "Fallback extracted fact", "evidence_chunk_ids": [cid], "confidence": 0.5}], "claims": [], "interpretations": [], "results": []}
    return {"ok": True}

def _safe_json_loads(raw: str) -> dict:
    candidates: list[str] = []
    try:
        x = json.loads(raw)
        if isinstance(x, dict):
            return x
    except json.JSONDecodeError:
        pass

    s, e = raw.find("{"), raw.rfind("}")
    if s != -1 and e != -1 and e > s:
        candidates.append(raw[s:e+1])

    # Try balanced-object extraction in case extra prose/truncated tails are present.
    start = raw.find("{")
    if start != -1:
        depth = 0
        in_str = False
        esc = False
        end = -1
        for i, ch in enumerate(raw[start:], start=start):
            if esc:
                esc = False
                continue
            if ch == "\\":
                esc = True
                continue
            if ch == '"':
                in_str = not in_str
                continue
            if in_str:
                continue
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    end = i
                    break
        if end != -1:
            candidates.append(raw[start:end+1])

    for c in candidates:
        try:
            x = json.loads(c)
            if isinstance(x, dict):
                return x
        except json.JSONDecodeError:
            continue

    raise ValueError("Model did not return valid JSON object")


def _extract_payload_from_prompt(prompt: str) -> dict[str, Any]:
    m = "INPUT:\n"; i = prompt.rfind(m)
    if i == -1: return {}
    try:
        v = json.loads(prompt[i+len(m):].strip())
        return v if isinstance(v, dict) else {}
    except json.JSONDecodeError:
        return {}
