"""LLM provider abstraction with role-specific clients."""

from __future__ import annotations

import json
import os
from abc import ABC, abstractmethod


class LLMProvider(ABC):
    """Abstract model provider for router/extractor/generator roles."""

    def __init__(self, model: str):
        self.model = model

    @abstractmethod
    def complete_json(self, prompt: str) -> dict:
        """Return JSON object for structured tasks."""

    @abstractmethod
    def complete_text(self, prompt: str) -> str:
        """Return freeform text output."""


class MockProvider(LLMProvider):
    """Deterministic local provider used by tests and offline demos."""

    def complete_json(self, prompt: str) -> dict:
        if "ROUTER_PLAN" in prompt:
            return {
                "intent": "comparison",
                "entities": ["KILT", "adaptive compression"],
                "filters": {"year_gte": 2024},
                "store_weights": {"vector": 0.35, "graph": 0.25, "result": 0.25, "obsidian": 0.15},
                "retrieval_budget": {"vector": 8, "graph": 4, "result": 6, "obsidian": 4},
                "response_mode": "report",
            }
        if "EXTRACTION" in prompt:
            return {
                "facts": [],
                "claims": [],
                "interpretations": [],
                "results": [],
            }
        return {}

    def complete_text(self, prompt: str) -> str:
        return "Grounded summary generated by mock provider."


class OpenAICompatibleProvider(LLMProvider):
    """OpenAI-compatible stub integration; requires external SDK wiring."""

    def complete_json(self, prompt: str) -> dict:
        raise NotImplementedError("Wire OpenAI client using OPENAI_API_KEY for production.")

    def complete_text(self, prompt: str) -> str:
        raise NotImplementedError("Wire OpenAI client using OPENAI_API_KEY for production.")


class AnthropicCompatibleProvider(LLMProvider):
    """Anthropic-compatible stub integration; requires external SDK wiring."""

    def complete_json(self, prompt: str) -> dict:
        raise NotImplementedError("Wire Anthropic client using ANTHROPIC_API_KEY for production.")

    def complete_text(self, prompt: str) -> str:
        raise NotImplementedError("Wire Anthropic client using ANTHROPIC_API_KEY for production.")


def build_provider(role: str) -> LLMProvider:
    """Build provider by role using environment configuration."""
    provider_name = os.getenv(f"{role.upper()}_PROVIDER", "mock").lower()
    model_name = os.getenv(f"{role.upper()}_MODEL", "mock-model")
    if provider_name == "mock":
        return MockProvider(model_name)
    if provider_name == "openai":
        return OpenAICompatibleProvider(model_name)
    if provider_name == "anthropic":
        return AnthropicCompatibleProvider(model_name)
    raise ValueError(f"Unknown provider: {provider_name}")


def render_json_prompt(template: str, payload: dict) -> str:
    return template + "\n\nINPUT:\n" + json.dumps(payload, indent=2)
