"""LLM provider abstraction with role-specific clients."""

from __future__ import annotations

import json
import os
from abc import ABC, abstractmethod
from typing import Any

from openai import OpenAI

from app.config import load_config


class LLMProvider(ABC):
    """Abstract model provider for router/extractor/generator roles."""

    def __init__(self, model: str):
        self.model = model

    @abstractmethod
    def complete_json(self, prompt: str) -> dict:
        """Return JSON object for structured tasks."""

    @abstractmethod
    def complete_text(self, prompt: str) -> str:
        """Return freeform text output."""


class MockProvider(LLMProvider):
    """Deterministic local provider used by tests and offline demos."""

    def complete_json(self, prompt: str) -> dict:
        if "ROUTER_PLAN" in prompt:
            return {
                "intent": "comparison",
                "entities": ["KILT", "adaptive compression"],
                "filters": {"year_gte": 2024},
                "store_weights": {"vector": 0.35, "graph": 0.25, "result": 0.25, "obsidian": 0.15},
                "retrieval_budget": {"vector": 8, "graph": 4, "result": 6, "obsidian": 4},
                "response_mode": "report",
            }

        if "EXTRACTION" in prompt:
            payload = _extract_payload_from_prompt(prompt)
            paper = payload.get("paper", {})
            chunks = payload.get("chunks", [])
            first_chunk_id = chunks[0].get("chunk_id", "c0") if chunks else "c0"
            first_chunk_text = chunks[0].get("text", "") if chunks else ""
            return {
                "facts": [
                    {
                        "text": paper.get("abstract") or first_chunk_text,
                        "evidence_chunk_ids": [first_chunk_id],
                        "confidence": 0.75,
                    }
                ],
                "claims": [
                    {
                        "claim_type": "performance",
                        "text": first_chunk_text[:280] or "The method improves retrieval performance.",
                        "evidence_chunk_ids": [first_chunk_id],
                        "support_type": "explicit",
                        "confidence": 0.72,
                    }
                ],
                "interpretations": [],
                "results": [],
            }
        return {}

    def complete_text(self, prompt: str) -> str:
        return "Grounded summary generated by mock provider."


class OpenAICompatibleProvider(LLMProvider):
    """OpenAI integration for router/extractor/generator."""

    def __init__(self, model: str, api_key: str | None = None):
        super().__init__(model)
        cfg = load_config()
        key = api_key or cfg.llm.openai_api_key or os.getenv("OPENAI_API_KEY")
        if not key:
            raise ValueError("OpenAI API key is required. Set [llm].openai_api_key in config/paperweb.toml.")
        self.client = OpenAI(api_key=key)

    def complete_json(self, prompt: str) -> dict:
        response = self.client.chat.completions.create(
            model=self.model,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[{"role": "user", "content": prompt}],
        )
        text = response.choices[0].message.content or "{}"
        return _safe_json_loads(text)

    def complete_text(self, prompt: str) -> str:
        response = self.client.chat.completions.create(
            model=self.model,
            temperature=0.2,
            messages=[{"role": "user", "content": prompt}],
        )
        return (response.choices[0].message.content or "").strip()


class AnthropicCompatibleProvider(LLMProvider):
    """Anthropic-compatible stub integration; requires external SDK wiring."""

    def complete_json(self, prompt: str) -> dict:
        raise NotImplementedError("Wire Anthropic client using ANTHROPIC_API_KEY for production.")

    def complete_text(self, prompt: str) -> str:
        raise NotImplementedError("Wire Anthropic client using ANTHROPIC_API_KEY for production.")


def build_provider(role: str) -> LLMProvider:
    """Build provider by role using configuration file settings."""
    cfg = load_config()
    role_cfg = getattr(cfg.llm, role)
    provider_name = role_cfg.provider.lower()
    model_name = role_cfg.model

    if provider_name == "mock":
        return MockProvider(model_name)
    if provider_name == "openai":
        return OpenAICompatibleProvider(model_name, api_key=cfg.llm.openai_api_key)
    if provider_name == "anthropic":
        return AnthropicCompatibleProvider(model_name)
    raise ValueError(f"Unknown provider in config for {role}: {provider_name}")


def render_json_prompt(template: str, payload: dict) -> str:
    return template + "\n\nINPUT:\n" + json.dumps(payload, indent=2)


def _safe_json_loads(raw: str) -> dict:
    try:
        loaded = json.loads(raw)
        if isinstance(loaded, dict):
            return loaded
    except json.JSONDecodeError:
        pass

    start = raw.find("{")
    end = raw.rfind("}")
    if start != -1 and end != -1 and end > start:
        return json.loads(raw[start : end + 1])
    raise ValueError("Model did not return valid JSON object")


def _extract_payload_from_prompt(prompt: str) -> dict[str, Any]:
    marker = "INPUT:\n"
    idx = prompt.rfind(marker)
    if idx == -1:
        return {}
    payload_text = prompt[idx + len(marker) :].strip()
    try:
        parsed = json.loads(payload_text)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        return {}
    return {}
